stages:
  - setup
  - build
  - test

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - venv/
    - node_modules/
    - bower_components/

before_script:
  - "echo we are working in $CI_PROJECT_DIR"

setup_python:
  stage: setup
  only:
    - dev_TUB_software
    - develop_gulp
  script:
    - "echo installing python dependencies in virtual environment"
    - "[ ! -d venv ] && virtualenv -p python3 venv"
    - "source venv/bin/activate"
    - "pip3 install -r requirements.txt"
    - "rm -rf content_submodule"

gulp_build_multilang:
  stage: build
  only:
    - develop_gulp
    - dev_TUB_software
  script:
    # install npm and all required packages
    - "git clone https://github.com/creationix/nvm.git ~/.nvm && cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`"
    - ". ~/.nvm/nvm.sh"
    - "nvm install 6"
    - "nvm use 6"
    - "nvm alias default 6"
    - "cd $CI_PROJECT_DIR"
    - "npm install"
    # workaround for not working git:// urls at mathjax repo
    - "git config --global url.'https://'.insteadOf git://"
    # we need gulp and bower globally
    - "npm install -g gulp bower"
    # add content as a submodule
    - "git submodule add --force -b dev_VBKM_content git@gitlab.tubit.tu-berlin.de:stefan.born/VEUNDMINT_TUB_Brueckenkurs.git ./content_submodule"	
    - "git submodule init"
    - "git submodule update"
    # build everything
    - "[ ! -d build ] && make -f tools/makefiles/multilang nopdf"
    # copy all files that were generated by gulp to a user directory that is symlinked from /var/www/gitlab-ci-test
    - "rsync -avr --exclude public/* /home/gitlab-runner/gitlab-ci"

gulp_build_physik:
  stage: build
  only:
    - dev_Physik_content
  script:
    # install npm and all required packages
    - "git clone https://github.com/creationix/nvm.git ~/.nvm && cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`"
    - ". ~/.nvm/nvm.sh"
    - "nvm install 6"
    - "nvm use 6"
    - "nvm alias default 6"
    - "cd $CI_PROJECT_DIR"
    - "npm install"
    # workaround for not working git:// urls at mathjax repo
    - "git config --global url.'https://'.insteadOf git://"
    # we need gulp and bower globally
    - "npm install -g gulp bower"
    # add content as a submodule
    - "git submodule add --force -b dev_Physik_content git@gitlab.tubit.tu-berlin.de:stefan.born/VEUNDMINT_TUB_Brueckenkurs.git ./content_submodule"	
    - "git submodule init"
    - "git submodule update"
    # build everything
    - "[ ! -d build ] && make all course=PhysikBK"
    # copy all files that were generated by gulp to a user directory that is symlinked from /var/www/gitlab-ci-test
    - "rsync -avr --exclude public/* /home/gitlab-runner/physikbk"

gulp_all_tests:
  stage: test
  only:
    - develop_gulp
    - dev_TUB_software
  script:
    - "source venv/bin/activate"
    - "export BASE_URL=http://guest43.mulf.tu-berlin.de/gitlab-ci-test/"
    - "export LC_ALL=en_US.UTF-8"
    - "export LANG=en_US.UTF-8"
    - "export LANGUAGE=en_US.UTF-8"
    - "cd src && green -s1 -vvv --run-coverage"
    - "coverage html"
    # move coverage report to /coverage
    - "rsync -avr htmlcov/* /home/gitlab-runner/gitlab-ci/coverage"
