cache:
  paths:
  - venv

test:
  script:
  # install everything and run tests
  - echo $CI_BUILD_REF_NAME
  - [ -d venv ] && virtualenv -p python3 venv
  - source venv/bin/activate
  - pip3 install -r requirements.txt
  - cd src
  - python -m unittest
