.TH TTH-COMMON 1
.SH NAME
latex2gif, ps2gif, ps2png \- Convert LaTeX files to bit map images
.SH SYNOPSIS
.B latex2gif
.I "file"
.br
.B ps2gif
.I file.ps file.gif
[\fIicon.gif\fP]
.br
.B ps2png
.I file.ps file.png
[\fIicon.png\fP]
.SH "DESCRIPTION"
.B latex2gif\fP,
.B ps2gif
and
.B ps2png
are scripts for converting files to bit map images
used by
.B tth
and
.BR ttm .


.SH "SEE ALSO"
.IR tth (1),
.IR ttm (1)
and
.I /usr/share/doc/tth/html/index.html
or
.I /usr/share/doc/ttm/html/ttm_manual.html
with your favourite browser.

.SH AUTHOR
This manual page was written by Ian Maclaine-cross <iml@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
