# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=200)),
                ('browser_type', models.CharField(max_length=1000)),
            ],
        ),
    ]
