# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0003_auto_20160919_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_id', models.CharField(max_length=50)),
                ('siteuxid', models.CharField(max_length=200)),
                ('section', models.PositiveSmallIntegerField()),
                ('maxpoints', models.PositiveSmallIntegerField()),
                ('intest', models.BooleanField(default=False)),
                ('type', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='score',
            name='intest',
        ),
        migrations.RemoveField(
            model_name='score',
            name='maxpoints',
        ),
        migrations.RemoveField(
            model_name='score',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='score',
            name='section',
        ),
        migrations.RemoveField(
            model_name='score',
            name='siteuxid',
        ),
        migrations.AlterField(
            model_name='score',
            name='rawinput',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
