# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0005_score_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
