# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veundmint_base', '0009_auto_20160920_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='veundmint_base.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('user', 'question')]),
        ),
    ]
