# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0010_auto_20160920_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='intest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='maxpoints',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='q_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='score',
            name='section',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='siteuxid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='score',
            name='uxid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='score',
            name='question',
        ),
    ]
