# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0011_auto_20161004_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteuxid', models.CharField(default='', max_length=200)),
                ('intest', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
