# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0013_auto_20161005_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='websiteaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
