# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0014_auto_20161107_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rawfeedback', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
