# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0017_auto_20161110_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprofile',
            name='study',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
