# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 15:56
from __future__ import unicode_literals

from django.db import migrations, models

def q_id_to_question(apps, schema_editor):
	Score = apps.get_model("veundmint_base", "Score")
	Question = apps.get_model("veundmint_base", "Question")
	for score in Score.objects.all():
		score.question, created = Question.objects.get_or_create(
			question_id = score.q_id,
			siteuxid = score.siteuxid,
			section = score.section,
			maxpoints = score.maxpoints,
			intest = score.intest
		)
		print (score.question)
		score.save()

def undo(apps, schema_editor):
	pass

class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0020_auto_20161207_1655'),
    ]

    operations = [
		migrations.RunPython(q_id_to_question, undo)
    ]
