# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veundmint_base', '0022_auto_20161207_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='score',
            name='intest',
        ),
        migrations.RemoveField(
            model_name='score',
            name='maxpoints',
        ),
        migrations.RemoveField(
            model_name='score',
            name='section',
        ),
        migrations.RemoveField(
            model_name='score',
            name='siteuxid',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('user', 'question')]),
        ),
    ]
