# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0024_remove_score_q_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='uxid',
        ),
    ]
