# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0026_auto_20161212_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veundmint_base.Site'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to=settings.AUTH_USER_MODEL),
        ),
    ]
