# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0027_auto_20161212_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='veundmint_base.Site'),
        ),
    ]
