# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0028_auto_20161212_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='siteuxid',
        ),
    ]
