# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0029_remove_question_siteuxid'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='points',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
