# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0031_auto_20161216_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='uxid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(max_length=100),
        ),
    ]
