# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0032_auto_20161216_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
