# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 04:38
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth import get_user_model
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password


def add_testrunner(apps, schema_editor):
	User.objects.create_user("testrunner", email="tester@tester.com", password="<>87c`}X&c8)2]Ja6E2cLDyr]*A$^3E")

def delete_testrunner(apps, schema_editor):
	User.objects.filter(username="testrunner").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('veundmint_base', '0034_auto_20161216_0516'),
    ]

    operations = [
		migrations.RunPython(add_testrunner, delete_testrunner)
    ]
