module.exports = {
	getNewUserData: function() {
	return {stats:{
		   "VBKM_FIRSTPAGE":{
		      "millis":1490750
		   },
		   "VBKM_MISCLOGIN":{
		      "millis":6000
		   },
		   "VBKM_MISCSETTINGS":{
		      "millis":22750
		   },
		   "VBKM01_START":{
		      "millis":4500
		   },
		   "VBKM01_VariablenTerme":{
		      "millis":741250,
		      "QFELD_1.1.3.QF1":{
		         "id":"QFELD_1.1.3.QF1",
		         "points":4,
		         "uxid":"ER1",
		         "siteuxid":"VBKM01_VariablenTerme",
		         "rawinput":"5",
		         "maxpoints":4,
		         "value":0,
		         "section":1,
		         "intest":false
		      },
		      "points":16,
		      "QFELD_1.1.3.QF2":{
		         "id":"QFELD_1.1.3.QF2",
		         "points":4,
		         "uxid":"ER2",
		         "siteuxid":"VBKM01_VariablenTerme",
		         "rawinput":"2",
		         "maxpoints":4,
		         "value":0,
		         "section":1,
		         "intest":false
		      },
		      "QFELD_1.1.3.QF3":{
		         "id":"QFELD_1.1.3.QF3",
		         "points":4,
		         "uxid":"ER3",
		         "siteuxid":"VBKM01_VariablenTerme",
		         "rawinput":"21",
		         "maxpoints":4,
		         "value":0,
		         "section":1,
		         "intest":false
		      },
		      "QFELD_1.1.3.QF4":{
		         "id":"QFELD_1.1.3.QF4",
		         "points":4,
		         "uxid":"LSFF1",
		         "siteuxid":"VBKM01_VariablenTerme",
		         "rawinput":"a/(a+b)",
		         "maxpoints":4,
		         "value":0,
		         "section":1,
		         "intest":false
		      },
		      "QFELD_1.1.3.QF5":{
		         "id":"QFELD_1.1.3.QF5",
		         "points":0,
		         "uxid":"LSFF2",
		         "siteuxid":"VBKM01_VariablenTerme",
		         "rawinput":"falsch",
		         "maxpoints":4,
		         "value":0,
		         "section":1,
		         "intest":false
		      }
		   },
		   "VBKM01_ZahlenIntro":{
		      "millis":7500
		   },
		   "VBKM_MISCCOURSEDATA":{
		      "millis":41000
		   }
		}}
	},
  getComplexUserData: function() {
    return {
      "active":true,
      "layout":{
        "fontadd":0,
        "menuactive":true
      },
      "configuration":{
        "stylecolor":"0",
        "CF_LOCAL":"1",
        "CF_USAGE":"1",
        "CF_TESTS":"1"
      },
      "scores":[
        {
          "uxid":"ER1",
          "maxpoints":4,
          "points":4,
          "siteuxid":"VBKM01_VariablenTerme",
          "section":1,
          "id":"QFELD_1.1.3.QF1",
          "intest":false,
          "value":0,
          "rawinput":"5",
          "state":1
        },
        {
          "uxid":"ER2",
          "maxpoints":4,
          "points":4,
          "siteuxid":"VBKM01_VariablenTerme",
          "section":1,
          "id":"QFELD_1.1.3.QF2",
          "intest":false,
          "value":0,
          "rawinput":"2",
          "state":1
        },
        {
          "uxid":"ER3",
          "maxpoints":4,
          "points":4,
          "siteuxid":"VBKM01_VariablenTerme",
          "section":1,
          "id":"QFELD_1.1.3.QF3",
          "intest":false,
          "value":0,
          "rawinput":"21",
          "state":1
        },
        {
          "uxid":"LSFF1",
          "maxpoints":4,
          "points":0,
          "siteuxid":"VBKM01_VariablenTerme",
          "section":1,
          "id":"QFELD_1.1.3.QF4",
          "intest":false,
          "value":0,
          "rawinput":"",
          "state":3
        },
        {
          "uxid":"LSFF2",
          "maxpoints":4,
          "points":0,
          "siteuxid":"VBKM01_VariablenTerme",
          "section":1,
          "id":"QFELD_1.1.3.QF5",
          "intest":false,
          "value":0,
          "rawinput":"",
          "state":3
        },
        {
          "uxid":"ERX1",
          "maxpoints":4,
          "points":0,
          "siteuxid":"VBKM01_VariablenTerme",
          "section":1,
          "id":"QFELD_1.1.3.QF6",
          "intest":false,
          "value":0,
          "rawinput":"",
          "state":3
        },
        {
          "uxid":"ERX2",
          "maxpoints":4,
          "points":0,
          "siteuxid":"VBKM01_VariablenTerme",
          "section":1,
          "id":"QFELD_1.1.3.QF7",
          "intest":false,
          "value":0,
          "rawinput":"",
          "state":3
        },
        {
          "uxid":"ERX3",
          "maxpoints":4,
          "points":0,
          "siteuxid":"VBKM01_VariablenTerme",
          "section":1,
          "id":"QFELD_1.1.3.QF8",
          "intest":false,
          "value":0,
          "rawinput":"",
          "state":3
        },
        {
          "uxid":"ERX11",
          "maxpoints":4,
          "points":0,
          "siteuxid":"VBKM01_VariablenTerme",
          "section":1,
          "id":"QFELD_1.1.3.QF9",
          "intest":false,
          "value":0,
          "rawinput":"",
          "state":3
        },
        {
          "uxid":"ERX12",
          "maxpoints":4,
          "points":0,
          "siteuxid":"VBKM01_VariablenTerme",
          "section":1,
          "id":"QFELD_1.1.3.QF10",
          "intest":false,
          "value":0,
          "rawinput":"",
          "state":3
        },
        {
          "uxid":"ERX13",
          "maxpoints":4,
          "points":0,
          "siteuxid":"VBKM01_VariablenTerme",
          "section":1,
          "id":"QFELD_1.1.3.QF11",
          "intest":false,
          "value":0,
          "rawinput":"",
          "state":3
        }
      ],
      "sites":[
        {
          "uxid":"SITE_VBKM_FIRSTPAGE",
          "millis":14000,
          "maxpoints":1,
          "points":1,
          "id":"",
          "intest":false,
          "section":""
        },
        {
          "uxid":"SITE_VBKM01_START",
          "millis":3750,
          "maxpoints":1,
          "points":1,
          "id":"",
          "intest":false,
          "section":""
        },
        {
          "uxid":"SITE_VBKM01_VariablenTerme",
          "millis":502000,
          "maxpoints":1,
          "points":1,
          "id":"",
          "intest":false,
          "section":""
        }
      ],
      "favorites":[
        {
          "type":"Tipp",
          "color":"00FF00",
          "text":"Eingangstest probieren",
          "pid":"html/sectionx2.1.0.html",
          "icon":"test01.png"
        }
      ],
      "history":{
        "globalmillis":519750,
        "commits":[
          [
            "CHEX:13d0be76bf7aeafffd97da9cf1b2c4956d0aca8a_CID:(MFR-TUB;;10000;;DE-MINT)",
            1477582854737,
            1479127993429
          ]
        ]
      },
      "login":{
        "type":0,
        "vname":"",
        "sname":"",
        "username":"",
        "password":"",
        "email":"",
        "variant":"std",
        "sgang":"",
        "uni":""
      },
      "signature":{
        "main":"MFR-TUB",
        "version":"10000",
        "localization":"DE-MINT"
      },
      "startertitle":"3.1 Willkommen",
      "scrollTop":0
    }
  }
}
